### PR TITLE
Add more information to the setup.py for cricket

### PR DESCRIPTION
**Pull request by phildini**
Per https://packaging.python.org/tutorials/distributing-packages/#project-urls
we can have even more helpful information in our package and on our PyPI page by
adding urls to the setup.py

### CODE REVIEW

**Comment by phildini** [comment]
Well, crap re: test failures. Ok, so apparently that setuptools option only exists for certain python versions. Hmm..

**Comment by freakboy3742** [comment]
Does it help if we specify `setuptools>=29.0` (or whatever the version where the key becomes legal)?

**Comment by phildini** [comment]
@freakboy3742 I'll play with it and see what's what. If that's an option that may be the best option.

**Comment by phildini** [comment]
Oh hey! This all passes now!

**Pull request merged**
